services:
  ha-fusion:
    container_name: ha-fusion
    image: ghcr.io/umarjamilpc/ha-fusion-2:latest
    volumes:
      - /path/to/ha-fusion:/app/data
    network_mode: bridge
    ports:
      - 5050:5050
    environment:
      TZ: Europe/Stockholm
      HASS_URL: http://192.168.1.241:8123
    restart: always
